version: 1
from: talpa-io/talpa-datalytics:testing


command:
  build:
    - "sudo /kickstart/flavor/flavor-build.sh"
  init:
  run:
  dev:
  test:
    - "cd /datalytics && vendor/bin/phpunit"

  info:
    - "env"
